services:
  whatsupdocker:
    image: getwud/wud:latest
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4000:3000

    restart: unless-stopped
