---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Watt-Monster:
    - Watt-Monster:
        href: https://{{HOMEPAGE_VAR_WATTMONSTER_IP}}:8006
        description: what ya wanna do?
        icon: proxmox
        siteMonitor: https://{{HOMEPAGE_VAR_WATTMONSTER_IP}}:8006
        widget: 
            type: proxmox
            url: https://{{HOMEPAGE_VAR_WATTMONSTER_IP}}:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: Watt-Monster
    
    - PFSense:
        href: https://{{HOMEPAGE_VAR_PFSENSE_IP}}/
        description: PFsense
        icon: pfsense
        widget:
            type: pfsense
            url: https://{{HOMEPAGE_VAR_PFSENSE_IP}}:443
            username: {{HOMEPAGE_VAR_PFSENSE_USER}}
            password: {{HOMEPAGE_VAR_PFSENSE_PASSWORD}}
            wan: vtnet0
            version: 2 # optional, defaults to 1 for api v1
            fields: ["load", "memory", "wanStatus"] # optional

    - TrueNas:
        href: http://{{HOMEPAGE_VAR_TRUENAS_IP}}
        icon: truenas
        widget:
            type: truenas
            url: http://{{HOMEPAGE_VAR_TRUENAS_IP}}
            key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
            enablePools: true
            nasType: core

    - Minecraft:
        href: https://{{HOMEPAGE_VAR_CRAFTY_IP}}:8443
        siteMonitor: https://{{HOMEPAGE_VAR_CRAFTY_IP}}:8443
        description: Crafty Controller
        icon: https://{{HOMEPAGE_VAR_CRAFTY_IP}}:8443/static/assets/images/logo_long.svg
        widget:
            type: minecraft
            url: udp://{{HOMEPAGE_VAR_CRAFTY_IP}}:25565

    - Jellyfin:
        href: http://{{HOMEPAGE_VAR_JELLYFIN_IP}}:8096
        description: Jellyfin
        icon: jellyfin
        widget:
            type: jellyfin
            url: http://{{HOMEPAGE_VAR_JELLYFIN_IP}}:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true

- Watt-Morpheus:
    - Watt-Morpheus:
        href: https://{{HOMEPAGE_VAR_WATTMORPHEUS_IP}}:8006
        description: cause my phone has more ram!
        icon: proxmox
        siteMonitor: https://{{HOMEPAGE_VAR_WATTMORPHEUS_IP}}:8006
        widget: 
            type: proxmox
            url: https://{{HOMEPAGE_VAR_WATTMORPHEUS_IP}}:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: Watt-Morpheus

    - Grafana:
        description: Monitoring
        icon: grafana
        href: http://{{HOMEPAGE_VAR_GRAFANA_IP}}:3000/d/IfgdXjtnk


    - Portainer:
        description: running containers on a potato
        href: https://{{HOMEPAGE_VAR_PORTAINER_IP}}:9443
        icon: portainer
        widget:
            type: portainer
            url: https://{{HOMEPAGE_VAR_PORTAINER_IP}}:9443
            env: 2
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}

- External Clicks:
    - Watt-Monster:
            href: https://{{HOMEPAGE_VAR_WATTMONSTER_EXT_IP}}:8006
            description: cause my phone has more ram!
            icon: proxmox
            siteMonitor: https://{{HOMEPAGE_VAR_WATTMONSTER_EXT_IP}}:8006

    - Watt-Morpheus:
            href: https://{{HOMEPAGE_VAR_WATTMORPHEUS_EXT_IP}}:8006
            description: cause my phone has more ram!
            icon: proxmox
            siteMonitor: https://{{HOMEPAGE_VAR_WATTMORPHEUS_EXT_IP}}:8006
            
    - Grafana External:
        description: Monitoring
        icon: grafana
        href: http://{{HOMEPAGE_VAR_GRAFANA_EXT_IP}}:3000/d/IfgdXjtnk

    - Portainer:
        description: running containers on a potato
        href: https://{{HOMEPAGE_VAR_PORTAINER_EXT_IP}}:9443
        icon: portainer
        
    - PFSense:
        href: https://{{HOMEPAGE_VAR_PFSENSE_EXT_IP}}/
        description: PFsense
        icon: pfsense