---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

background:
  image: /images/on_duty_by_neytirix_ddff7cy.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 80 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  

  opacity: 70 # 0-100

# cardBlur: md # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur