services:
 
  influxdb2:
    image: influxdb:2
    container_name: influx-db2
    restart: unless-stopped
    ports:
      - 8086:8086

    networks:
      - influx-graf

    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs 
      DOCKER_INFLUXDB_INIT_BUCKET: home
  
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
secrets:
  influxdb2-admin-username:
    file: .env.influxdb2-admin-username
  influxdb2-admin-password:
    file: .env.influxdb2-admin-password
  influxdb2-admin-token:
    file: .env.influxdb2-admin-token
  influxdb2-mount-path:
    file: .env

volumes:
  influxdb2-data:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: "${MOUNT_PATH}/influxdb2-data"

  influxdb2-config:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: "${MOUNT_PATH}/influxdb2-config"

networks:
  influx-graf:
    name: InfluxGraf
    driver: bridge