services:
  gitlab:
    image: gitlab/gitlab-ce:17.5.1-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: 'gitlab.example.com'

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
      #   gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '443:443'
      - '2424:22'
    volumes:
      - type: volume
        source: gitlab-config
        target: /etc/gitlab
      - type: volume
        source: gitlab-data
        target: /var/log/gitlab
      - type: volume
        source: gitlab-logs
        target: /var/opt/gitlab
    shm_size: '256m'

secrets:
  gitlab-mount-path:
    file: .env.mnt-path

volumes:
  gitlab-config:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: './config'
  gitlab-data:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '${MOUNT_PATH}/srv/gitlab/logs'
  gitlab-logs:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '${MOUNT_PATH}/srv/gitlab/data'