services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - type: volume
        source: syncthing-configs
        target: /var/syncthing
      - type: volume
        source: myPhotos-volume
        target: /media/MyPhotos
    network_mode: "host"
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  myPhotos-volume:
    driver: local
    driver_opts:
      type: cifs
      o: "username=${SMB_USER},password=${SMB_PASSWORD},uid=${SMB_UID},gid=${SMB_GID}"
      device: "//${TRUENAS_IP}/${TRUENAS_MOUNT_PATH}"

  syncthing-configs:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: ${MOUNT_PATH}/
