services:
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    user: "telegraf:${USER_GID}" # Pass the GID dynamically
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    restart: unless-stopped
